### ISSUE TITLE
Something missing in documentation ?

### ISSUE THREAD

**Issue by AndKe** [datagutten/tools#1]
when executing, I get this; 

```
andre@Loke:~/Downloads/nrk-master$ php newsrip.php http://www.nrk.no/video/PS*191528
PHP Warning:  require(config.php): failed to open stream: No such file or directory in /home/andre/Downloads/nrk-master/functions.php on line 28
PHP Fatal error:  require(): Failed opening required 'config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/andre/Downloads/nrk-master/functions.php on line 28
andre@Loke:~/Downloads/nrk-master$
```

I am not sure where config.php is supposed to come from. ?
Thank you for the script, looking forward to get it working :)

**Comment by datagutten** [comment]
First of all, you are posting this issue in the wrong repo, this is the tools repo, you seem to be talking about nrk.
The file you are missing is in the repo as config_sample.php, you need to customize it with the path where you want the files to be saved and rename it to config.php

**Comment by AndKe** [comment]
thank you, that solved it :)  - the script worked great.
